from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_play(object):
    def setupUi(self, play):
        self.centralwidget = QtWidgets.QWidget(play)
        # Create bg
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.bg.setPixmap(QtGui.QPixmap("sourcepic\\bgplain1.png"))
        # Create framebox
        self.framebox = QtWidgets.QLabel(self.centralwidget)
        self.framebox.setGeometry(QtCore.QRect(150, 25, 650, 650))
        self.framebox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framebox.setPixmap(QtGui.QPixmap("sourcepic\\bg4.jpg"))
        # Create gridLayoutWidget
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(149, 69, 561, 561))
        self.gridframe = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridframe.setContentsMargins(0, 0, 0, 0)
        # Create all label
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setFont(font)
        self.label_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setFont(font)
        self.label_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_14, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)

        self.gridframe.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setFont(font)
        self.label_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.gridframe.addWidget(self.label_16, 3, 3, 1, 1)

        self.highscorelbl = QtWidgets.QLabel(self.centralwidget)
        self.highscorelbl.setGeometry(QtCore.QRect(760, 130, 161, 61))
        self.highscorelbl.setText("HIGH SCORE:")
        font.setPointSize(10)
        self.highscorelbl.setFont(font)
        self.highscorelbl.setFrameShape(QtWidgets.QFrame.Panel)
        # self.highscorelbl.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.scorelbl = QtWidgets.QLabel(self.centralwidget)
        self.scorelbl.setGeometry(QtCore.QRect(760, 260, 161, 61))
        self.scorelbl.setFont(font)
        self.scorelbl.setFrameShape(QtWidgets.QFrame.Panel)
        # self.scorelbl.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.cScorelbl = QtWidgets.QLabel(self.centralwidget)
        self.cScorelbl.setText("Current score")
        font.setPointSize(9)
        self.cScorelbl.setGeometry(QtCore.QRect(760, 210, 161, 41))
        self.cScorelbl.setFont(font)
        self.cScorelbl.setAlignment(QtCore.Qt.AlignCenter)

        self.hScorelbl = QtWidgets.QLabel(self.centralwidget)
        self.hScorelbl.setGeometry(QtCore.QRect(760, 80, 161, 41))
        self.hScorelbl.setText("High Score")
        self.hScorelbl.setFont(font)
        self.hScorelbl.setAlignment(QtCore.Qt.AlignCenter)
